### ISSUE TITLE
Is this usable with AMDVBT2_Setup_200917?

### ISSUE THREAD

**Issue by mzso** [rvs76/AstrometaSwitch#1]
Hi!

This is the only driver Astrometa provided that's labelled for Windows 10. But they failed to provide a DVB-C variant...
Should I expect any issues?

(Funnily the version number of the package suggests a 2020-09-17 date, in device manager there's a 2017 date, but the last modification date for files in the archive islate 2019. But I guess it's the latest.)

**Comment by rvs76** [comment]
I haven't owned this tuner for three years and I haven't tested the latest drivers. You have to test ...

**Comment by mzso** [comment]
[**@rvs76**](https://github.com/rvs76) commented on [2021. ápr. 27. 21:41 CEST](https://github.com/rvs76/AstrometaSwitch/issues/1#issuecomment-827871511 "2021-04-27T19:41:17Z - Replied by Github Reply Comments"):
> I haven't owned this tuner for three years and I haven't tested the latest drivers. You have to test ...

Did it die?
Anyway I tried it, it seems to work fine. And the new driver seems a lot faster at switching channels and somewhat faster starting up.

**Comment by rvs76** [comment]
The tuner cases are very fragile. The first one,  my 6 year old daughter stepping on it in 2016. The second one, my 15 month old son who broke it

**Comment by mzso** [comment]
So, since I ran into no issues I guess this should be closed.


[**@rvs76**](https://github.com/rvs76) commented on [2021. ápr. 28. 22:49 CEST](https://github.com/rvs76/AstrometaSwitch/issues/1#issuecomment-828769481 "2021-04-28T20:49:48Z - Replied by Github Reply Comments"):
> The tuner cases are very fragile. The first one, my 6 year old daughter stepping on it in 2016. The second one, my 15 month old son who broke it

I have two, the second updated variant (which has a green LED) feels a bit sturdier. For the first one I needed to fix the fractured soldering to the antenna connector.
